epochs = 1
batch_size = 4
num_batches = 2
learning_rate = .1
article_csv_selector = "text"
label_csv_selector = "label"
title_csv_selector = "title"
bert_output_dim = 768
csv_rows_limit = batch_size * num_batches
